name: Lint Workflows

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actionlint.yaml"

permissions:
  contents: read

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Lint GitHub workflows
        uses: rhysd/actionlint@v1.7.12
